import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "tatti shef",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
        <link 
          href="https://fonts.googleapis.com/css2?family=IM+Fell+Double+Pica:ital,wght@0,400;1,400&display=swap" 
          rel="stylesheet"
        />
      </head>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}
